export type MusicMemoryLibraryItem = {
  title: string;
  artist?: string;
  source?: string;
  moods: string[];
  scenes: string[];
  time_feelings: string[];
  reason: string;
  keywords: string[];
};

export const musicMemoryLibrary: MusicMemoryLibraryItem[] = [
  {
    title: "那些花儿",
    artist: "朴树",
    source: "华语青春 OST",
    moods: ["毕业", "怀旧", "青春"],
    scenes: ["校园", "教室", "操场"],
    time_feelings: ["傍晚", "毕业季"],
    reason: "像一张快褪色的毕业合照，适合空教室和迟迟没有说出口的告别。",
    keywords: ["华语青春OST", "校园毕业感", "吉他", "告别"],
  },
  {
    title: "送别",
    artist: "朴树",
    source: "电影感华语民谣",
    moods: ["告别", "安静", "旧时光"],
    scenes: ["教室", "车站", "走廊"],
    time_feelings: ["黄昏", "散场"],
    reason: "旋律自带旧胶片的远景感，适合最后一课之后的空白。",
    keywords: ["毕业", "华语青春OST", "旧胶片"],
  },
  {
    title: "平凡之路",
    artist: "朴树",
    source: "华语青春 OST",
    moods: ["行走", "青春", "释然"],
    scenes: ["街道", "校园", "旅途"],
    time_feelings: ["傍晚", "路上"],
    reason: "适合把普通空间变成人生片段，带一点向远方走去的余温。",
    keywords: ["青春", "路上", "华语OST"],
  },
  {
    title: "小幸运",
    artist: "田馥甄",
    source: "校园电影 OST",
    moods: ["青春", "暗恋", "温柔"],
    scenes: ["教室", "窗边", "校园"],
    time_feelings: ["午后", "毕业前"],
    reason: "明亮但不刺眼，适合教室窗光和被保存下来的青春心事。",
    keywords: ["华语青春OST", "校园", "暗恋"],
  },
  {
    title: "匆匆那年",
    artist: "王菲",
    source: "华语青春 OST",
    moods: ["遗憾", "回望", "柔软"],
    scenes: ["校园", "旧照片", "走廊"],
    time_feelings: ["多年以后", "黄昏"],
    reason: "适合带有回望感的空间，像把青春压在相册透明页里。",
    keywords: ["青春", "旧照片", "OST"],
  },
  {
    title: "后来",
    artist: "刘若英",
    source: "华语记忆流行",
    moods: ["错过", "怀旧", "旁白"],
    scenes: ["餐桌", "街角", "房间"],
    time_feelings: ["夜晚", "多年以后"],
    reason: "适合有私人叙事的空间，把未说完的话变成慢镜头。",
    keywords: ["华语", "记忆", "夜晚"],
  },
  {
    title: "当时的月亮",
    artist: "王菲",
    source: "华语 city pop",
    moods: ["月光", "都市", "疏离"],
    scenes: ["窗边", "街道", "夜晚餐桌"],
    time_feelings: ["深夜", "月色"],
    reason: "有都市夜色和旧唱片的质感，适合冷暖交错的空间。",
    keywords: ["city pop", "夜晚", "月光"],
  },
  {
    title: "梦中人",
    artist: "王菲",
    source: "华语 city pop",
    moods: ["迷离", "港风", "霓虹"],
    scenes: ["街角", "房间", "雨夜"],
    time_feelings: ["深夜", "梦里"],
    reason: "带有王家卫式的晕眩和距离感，适合霓虹、玻璃和潮湿街道。",
    keywords: ["Wong Kar Wai", "city pop", "雨夜城市感"],
  },
  {
    title: "暧昧",
    artist: "王菲",
    source: "港风电影感",
    moods: ["暧昧", "克制", "夜色"],
    scenes: ["餐桌", "窗边", "走廊"],
    time_feelings: ["夜晚", "停顿"],
    reason: "适合有低声对话感的画面，像灯下没有被确认的关系。",
    keywords: ["港风", "餐桌胶片感", "夜晚"],
  },
  {
    title: "喜欢你",
    artist: "陈洁仪",
    source: "华语 city pop",
    moods: ["温柔", "复古", "都市"],
    scenes: ["餐桌", "客厅", "夜街"],
    time_feelings: ["晚上", "旧唱片"],
    reason: "有温暖灯光和旧电台的质感，适合餐桌、房间和微醺色温。",
    keywords: ["city pop", "餐桌", "复古"],
  },
  {
    title: "南海姑娘",
    artist: "邓丽君",
    source: "华语复古流行",
    moods: ["复古", "温柔", "旧日"],
    scenes: ["庭院", "餐桌", "窗边"],
    time_feelings: ["午后", "旧唱机"],
    reason: "像一只老唱机里的暖风，适合春日庭院和泛黄的墙面。",
    keywords: ["复古", "春日庭院感", "华语"],
  },
  {
    title: "夜来香",
    artist: "邓丽君",
    source: "中式复古流行",
    moods: ["夜色", "旧上海", "香气"],
    scenes: ["庭院", "餐桌", "夜晚"],
    time_feelings: ["夜晚", "旧梦"],
    reason: "适合带有花香、灯影和旧上海气息的空间记忆。",
    keywords: ["旧上海", "夜晚", "餐桌胶片感"],
  },
  {
    title: "良夜不能留",
    artist: "姚莉",
    source: "中式电影配乐感",
    moods: ["旧上海", "朦胧", "留恋"],
    scenes: ["餐桌", "窗边", "街角"],
    time_feelings: ["深夜", "散场"],
    reason: "让空间像一帧老电影里的室内戏，温柔但带一点旧梦。",
    keywords: ["中式电影配乐", "旧上海", "深夜"],
  },
  {
    title: "花样的年华",
    artist: "周璇",
    source: "中式电影配乐感",
    moods: ["怀旧", "旧电影", "优雅"],
    scenes: ["走廊", "餐桌", "房间"],
    time_feelings: ["旧时光", "夜晚"],
    reason: "适合王家卫式空间，像慢慢经过门框的一束光。",
    keywords: ["Wong Kar Wai", "中式电影配乐", "old film"],
  },
  {
    title: "Yumeji's Theme",
    artist: "Shigeru Umebayashi",
    source: "In the Mood for Love",
    moods: ["克制", "暧昧", "慢镜头"],
    scenes: ["走廊", "餐桌", "雨夜"],
    time_feelings: ["夜晚", "停顿"],
    reason: "最适合慢速空间记忆，把走廊、餐桌和背影变成电影里的等待。",
    keywords: ["王家卫", "电影配乐", "慢"],
  },
  {
    title: "2046 Main Theme",
    artist: "Shigeru Umebayashi",
    source: "2046",
    moods: ["未来怀旧", "孤独", "夜车"],
    scenes: ["酒店", "窗边", "夜街"],
    time_feelings: ["深夜", "失眠"],
    reason: "适合深灰蓝黑的空间，把现代感和旧记忆缝在一起。",
    keywords: ["王家卫", "深夜", "电影配乐"],
  },
  {
    title: "Merry Christmas Mr. Lawrence",
    artist: "Ryuichi Sakamoto",
    source: "电影配乐",
    moods: ["清冷", "庄重", "回忆"],
    scenes: ["教室", "窗边", "雨后"],
    time_feelings: ["冬日", "清晨"],
    reason: "钢琴线条清澈，适合空旷空间里忽然涌起的记忆。",
    keywords: ["电影配乐", "钢琴", "清冷"],
  },
  {
    title: "Rain",
    artist: "Ryuichi Sakamoto",
    source: "The Last Emperor",
    moods: ["雨", "东方", "克制"],
    scenes: ["雨后街角", "庭院", "窗边"],
    time_feelings: ["雨后", "黄昏"],
    reason: "有东方电影的湿润质感，适合雨后街角和深色屋檐。",
    keywords: ["中式电影配乐", "雨夜城市感", "东方"],
  },
  {
    title: "The Sheltering Sky Theme",
    artist: "Ryuichi Sakamoto",
    source: "电影配乐",
    moods: ["辽阔", "孤独", "远方"],
    scenes: ["街道", "窗口", "空房间"],
    time_feelings: ["傍晚", "旅途"],
    reason: "适合空间里带有远方和离别感的画面，像一段很慢的旁白。",
    keywords: ["电影配乐", "旅途", "孤独"],
  },
  {
    title: "Mizu No Naka No Bagatelle",
    artist: "Ryuichi Sakamoto",
    source: "ambient piano",
    moods: ["水感", "安静", "透明"],
    scenes: ["雨后", "窗边", "庭院"],
    time_feelings: ["清晨", "雨后"],
    reason: "像水面下的钢琴，适合潮湿、透明、低饱和的空间。",
    keywords: ["ambient", "雨后", "钢琴"],
  },
  {
    title: "Aqua",
    artist: "Ryuichi Sakamoto",
    source: "ambient piano",
    moods: ["安静", "柔软", "水光"],
    scenes: ["窗边", "房间", "庭院"],
    time_feelings: ["清晨", "午后"],
    reason: "适合柔和自然光，把空间里的细微安静放大。",
    keywords: ["ambient", "清晨", "自然光"],
  },
  {
    title: "River Flows in You",
    artist: "Yiruma",
    source: "piano memory",
    moods: ["柔和", "青春", "回忆"],
    scenes: ["教室", "房间", "窗边"],
    time_feelings: ["午后", "青春期"],
    reason: "适合较明亮的青春空间，像一段被保存在日记里的钢琴旋律。",
    keywords: ["钢琴", "校园", "柔和"],
  },
  {
    title: "Kiss the Rain",
    artist: "Yiruma",
    source: "piano memory",
    moods: ["雨", "温柔", "怀旧"],
    scenes: ["雨后街角", "窗边", "房间"],
    time_feelings: ["雨天", "夜晚"],
    reason: "适合雨后的玻璃和街灯，情绪直接但不喧哗。",
    keywords: ["雨夜城市感", "钢琴", "温柔"],
  },
  {
    title: "二泉映月",
    artist: "华彦钧",
    source: "国风 / 民乐记忆",
    moods: ["苍凉", "月色", "旧城"],
    scenes: ["江南", "庭院", "夜街"],
    time_feelings: ["夜晚", "旧时光"],
    reason: "二胡的线条适合有历史感和月色的空间，带一点深处的孤独。",
    keywords: ["国风ambient", "江南", "月色"],
  },
  {
    title: "春江花月夜",
    source: "国风民乐",
    moods: ["江南", "春日", "月光"],
    scenes: ["庭院", "水边", "花园"],
    time_feelings: ["春夜", "月色"],
    reason: "适合花、庭院和水气，把春日空间推向古典记忆。",
    keywords: ["国风ambient", "春日庭院感", "江南"],
  },
  {
    title: "平湖秋月",
    source: "江南民乐",
    moods: ["湖光", "安静", "江南"],
    scenes: ["庭院", "水边", "窗边"],
    time_feelings: ["秋夜", "月光"],
    reason: "像一层薄薄的水光，适合江南式的安静和留白。",
    keywords: ["江南民谣感", "国风", "月光"],
  },
  {
    title: "渔舟唱晚",
    source: "古筝曲",
    moods: ["归来", "黄昏", "水面"],
    scenes: ["江南", "庭院", "河边"],
    time_feelings: ["傍晚", "日落"],
    reason: "适合黄昏水边和院落，把画面变成缓慢归家的感觉。",
    keywords: ["古筝", "江南民谣感", "黄昏"],
  },
  {
    title: "高山流水",
    source: "古琴曲",
    moods: ["清雅", "山水", "留白"],
    scenes: ["庭院", "书房", "窗边"],
    time_feelings: ["清晨", "静夜"],
    reason: "适合简洁、留白、带木质或自然光的空间。",
    keywords: ["国风ambient", "古琴", "留白"],
  },
  {
    title: "梅花三弄",
    source: "古琴曲",
    moods: ["清冷", "冬日", "克制"],
    scenes: ["庭院", "窗边", "老屋"],
    time_feelings: ["冬天", "清晨"],
    reason: "适合有冷光和旧木气息的空间，克制而不空。",
    keywords: ["古琴", "中式电影配乐", "清冷"],
  },
  {
    title: "雨碎江南",
    source: "国风 ambient direction",
    moods: ["雨", "江南", "潮湿"],
    scenes: ["雨后街角", "庭院", "屋檐"],
    time_feelings: ["雨夜", "清晨"],
    reason: "以古琴、笛子和环境底噪构成，适合湿润的江南空间。",
    keywords: ["国风ambient", "雨夜城市感", "江南"],
  },
  {
    title: "檐下风铃",
    source: "国风 ambient direction",
    moods: ["风", "春日", "安静"],
    scenes: ["春日天井", "庭院", "窗边"],
    time_feelings: ["午后", "春天"],
    reason: "适合天井、花影和旧墙，像很轻的风穿过院子。",
    keywords: ["春日庭院感", "国风ambient", "风铃"],
  },
  {
    title: "南方小院",
    source: "江南民谣 direction",
    moods: ["温柔", "生活", "春日"],
    scenes: ["天井", "庭院", "餐桌"],
    time_feelings: ["午后", "傍晚"],
    reason: "木吉他和少量民乐适合生活感空间，像旧相册里的南方下午。",
    keywords: ["江南民谣感", "春日庭院感", "木吉他"],
  },
  {
    title: "水边旧事",
    source: "江南民谣 direction",
    moods: ["水气", "旧事", "慢"],
    scenes: ["河边", "雨后", "庭院"],
    time_feelings: ["黄昏", "雨后"],
    reason: "适合低饱和、潮湿、带一点旧故事的空间。",
    keywords: ["江南", "民谣", "雨后"],
  },
  {
    title: "雨巷",
    source: "东方氛围电子 direction",
    moods: ["潮湿", "夜色", "迷离"],
    scenes: ["雨后街角", "巷子", "街道"],
    time_feelings: ["深夜", "雨后"],
    reason: "电子底噪和远处节拍适合雨夜街角，不会变成普通 lo-fi。",
    keywords: ["东方氛围电子", "雨夜城市感", "街角"],
  },
  {
    title: "霓虹潮汐",
    source: "东方氛围电子 direction",
    moods: ["霓虹", "都市", "失眠"],
    scenes: ["街角", "窗边", "夜街"],
    time_feelings: ["深夜", "凌晨"],
    reason: "适合蓝黑色城市空间，像霓虹在雨水里缓慢扩散。",
    keywords: ["东方氛围电子", "雨夜城市感", "霓虹"],
  },
  {
    title: "旧楼电梯",
    source: "东方氛围电子 direction",
    moods: ["旧楼", "机械", "孤独"],
    scenes: ["走廊", "电梯", "公寓"],
    time_feelings: ["深夜", "等待"],
    reason: "有轻微机械声和低频，适合楼道、门口和城市孤独感。",
    keywords: ["ambient", "城市", "深夜"],
  },
  {
    title: "蓝色出租车",
    source: "雨夜城市 direction",
    moods: ["流动", "雨夜", "电影"],
    scenes: ["街道", "车窗", "雨后街角"],
    time_feelings: ["凌晨", "路上"],
    reason: "适合车窗外的雨和城市灯光，让画面像夜行电影。",
    keywords: ["雨夜城市感", "电影感", "电子"],
  },
  {
    title: "Midnight Pretenders",
    artist: "Tomoko Aran",
    source: "city pop",
    moods: ["都市", "复古", "夜色"],
    scenes: ["餐桌", "街道", "窗边"],
    time_feelings: ["深夜", "旧唱片"],
    reason: "复古律动适合夜晚城市和暖色室内，带一点霓虹边缘。",
    keywords: ["city pop", "雨夜城市感", "复古"],
  },
  {
    title: "Plastic Love",
    artist: "Mariya Takeuchi",
    source: "city pop",
    moods: ["都市", "流动", "复古"],
    scenes: ["夜街", "餐桌", "车窗"],
    time_feelings: ["夜晚", "周末"],
    reason: "适合带有旧都市感的画面，但要用于较明亮、流动的空间。",
    keywords: ["city pop", "复古", "都市"],
  },
  {
    title: "Remember Summer Days",
    artist: "Anri",
    source: "city pop",
    moods: ["夏日", "记忆", "轻盈"],
    scenes: ["庭院", "窗边", "街道"],
    time_feelings: ["夏天", "傍晚"],
    reason: "适合有夏日余温和旧照片感的空间，明亮但不过分甜。",
    keywords: ["city pop", "夏日", "庭院"],
  },
  {
    title: "Sweet Love",
    artist: "Junko Ohashi",
    source: "city pop",
    moods: ["暖色", "餐桌", "夜晚"],
    scenes: ["餐桌", "客厅", "夜街"],
    time_feelings: ["夜晚", "旧电台"],
    reason: "适合餐桌胶片感，像背景里一台小音箱正在播放旧歌。",
    keywords: ["city pop", "餐桌胶片感", "夜晚"],
  },
  {
    title: "餐桌灯下",
    source: "table film direction",
    moods: ["家庭", "温暖", "沉默"],
    scenes: ["餐桌", "厨房", "客厅"],
    time_feelings: ["晚饭后", "夜晚"],
    reason: "以低音提琴、轻鼓刷和环境声组成，适合晚餐后的静默。",
    keywords: ["餐桌胶片感", "old film", "爵士"],
  },
  {
    title: "碗筷余温",
    source: "table film direction",
    moods: ["生活", "亲密", "余温"],
    scenes: ["餐桌", "厨房", "家"],
    time_feelings: ["晚餐", "夜晚"],
    reason: "让餐桌像一段家庭电影的尾声，保留碗筷和灯光的温度。",
    keywords: ["餐桌", "胶片", "家庭"],
  },
  {
    title: "After LIKE",
    artist: "IVE",
    source: "K-pop",
    moods: ["明亮", "自信", "青春"],
    scenes: ["校园", "街道", "花园"],
    time_feelings: ["白天", "周末"],
    reason: "适合色彩明亮、年轻、带自我表达感的空间，不适合过暗画面。",
    keywords: ["kpop", "青春", "明亮"],
  },
  {
    title: "Ditto",
    artist: "NewJeans",
    source: "K-pop",
    moods: ["校园", "怀旧", "录像带"],
    scenes: ["教室", "走廊", "操场"],
    time_feelings: ["冬日", "青春期"],
    reason: "带有 DV 和校园记忆的质感，非常适合旧教室、走廊和青春影像。",
    keywords: ["kpop", "校园毕业感", "录像带"],
  },
  {
    title: "Hype Boy",
    artist: "NewJeans",
    source: "K-pop",
    moods: ["青春", "轻盈", "城市"],
    scenes: ["街道", "校园", "房间"],
    time_feelings: ["下午", "周末"],
    reason: "适合年轻、轻快、带一点城市生活感的空间。",
    keywords: ["kpop", "city", "青春"],
  },
  {
    title: "Either Way",
    artist: "IVE",
    source: "K-pop",
    moods: ["柔软", "成长", "青春"],
    scenes: ["教室", "房间", "窗边"],
    time_feelings: ["傍晚", "独处"],
    reason: "比强节拍 K-pop 更适合 HearSpace，能承接柔和的成长叙事。",
    keywords: ["kpop", "青春", "柔和"],
  },
  {
    title: "Palette",
    artist: "IU",
    source: "K-pop / Korean pop",
    moods: ["成长", "温柔", "自我"],
    scenes: ["房间", "窗边", "餐桌"],
    time_feelings: ["夜晚", "独处"],
    reason: "适合私人空间和自我旁白，像写给自己的慢速信件。",
    keywords: ["kpop", "房间", "温柔"],
  },
  {
    title: "Through the Night",
    artist: "IU",
    source: "Korean ballad",
    moods: ["夜晚", "温柔", "思念"],
    scenes: ["窗边", "房间", "夜晚餐桌"],
    time_feelings: ["深夜", "睡前"],
    reason: "适合深夜空间，像灯下没有发出的语音消息。",
    keywords: ["kpop", "深夜", "温柔"],
  },
  {
    title: "Love wins all",
    artist: "IU",
    source: "Korean ballad",
    moods: ["电影", "深情", "末日浪漫"],
    scenes: ["街道", "房间", "雨夜"],
    time_feelings: ["夜晚", "逃离"],
    reason: "适合戏剧性更强的空间，把普通画面推向电影叙事。",
    keywords: ["kpop", "电影感", "夜晚"],
  },
  {
    title: "夜航班",
    source: "rain city ambient direction",
    moods: ["孤独", "流动", "蓝黑"],
    scenes: ["机场", "车窗", "街角"],
    time_feelings: ["凌晨", "路上"],
    reason: "适合冷色、移动、独自一人的城市片段。",
    keywords: ["雨夜城市感", "东方氛围电子", "凌晨"],
  },
  {
    title: "黑胶晚风",
    source: "old film archive direction",
    moods: ["复古", "暖风", "档案"],
    scenes: ["餐桌", "客厅", "庭院"],
    time_feelings: ["夜晚", "旧唱片"],
    reason: "像一张唱片内页，适合所有带旧物、暖灯和轻微颗粒的空间。",
    keywords: ["old film archive", "餐桌胶片感", "复古"],
  },
  {
    title: "春日放映",
    source: "spring courtyard direction",
    moods: ["春天", "花影", "柔软"],
    scenes: ["春日天井", "庭院", "花园"],
    time_feelings: ["午后", "春天"],
    reason: "适合花园、天井和墙面光影，把空间变成私人放映厅。",
    keywords: ["春日庭院感", "花园", "胶片"],
  },
  {
    title: "毕业钟声",
    source: "campus memory direction",
    moods: ["毕业", "空旷", "青春"],
    scenes: ["教室", "校园", "走廊"],
    time_feelings: ["傍晚", "毕业季"],
    reason: "以远处铃声、慢钢琴和磁带底噪组成，适合最后一课式画面。",
    keywords: ["校园毕业感", "华语青春OST", "慢钢琴"],
  },
  {
    title: "旧课桌抽屉",
    source: "campus memory direction",
    moods: ["怀旧", "秘密", "青春"],
    scenes: ["教室", "课桌", "窗边"],
    time_feelings: ["午后", "毕业前"],
    reason: "适合有课桌、纸张、窗光的空间，像抽屉里没带走的纸条。",
    keywords: ["校园", "毕业", "旧物"],
  },
];
